import { randomUUID } from 'node:crypto'; import { many, one, query } from './base.js'; import { int, text, textArray, uuid } from '../sql.js';
export function deposits(databaseUrl) { return {
  insertDeposit: async (d) => {
    try { await query(databaseUrl, `begin; insert into source_deposit (id,submitted_by,filename,sha256,declared_rights,intended_title,intended_author,status,created_at) values (${uuid(d.id)},${uuid(d.submittedBy)},${text(d.filename)},${text(d.sha256)},${text(d.declaredRights)},${text(d.intendedTitle)},${text(d.intendedAuthor)},'staged',${text(d.createdAt)}::timestamptz); commit;`); return d; }
    catch (error) { if (/unique|duplicate/i.test(error.message)) throw new Error('An identical source artifact has already been deposited.'); throw error; }
  },
  retrieveDeposit: async ({ depositId, actor }) => {
    const taskId = randomUUID(); const auditId = randomUUID();
    const result = await one(databaseUrl, `begin; with changed as (update source_deposit set status='retrieved',retrieved_at=now(),retrieved_by=${uuid(actor)} where id=${uuid(depositId)} and status='staged' returning id,filename,sha256,declared_rights,intended_title as "intendedTitle",intended_author as "intendedAuthor",status,submitted_by as "submittedBy",retrieved_at as "retrievedAt",retrieved_by as "retrievedBy") , task as (insert into editorial_task (id,deposit_id,type,status,assignee_role) select ${uuid(taskId)},id,'intake-review','open','literary-custodian' from changed returning id,deposit_id as "depositId",type,status,assignee_role as "assigneeRole",created_at as "createdAt") , audit as (insert into audit_event (id,type,subject_id,actor_id,actor_label) select ${uuid(auditId)},'deposit.retrieved',id,${uuid(actor)},'user' from changed) select row_to_json(x) from (select (select row_to_json(changed) from changed) as deposit,(select row_to_json(task) from task) as task) x; commit;`);
    if (!result?.deposit) throw new Error('Deposit is no longer in the required state.'); return result;
  },
  findDeposit: (id) => one(databaseUrl, `select row_to_json(d) from (select id,filename,status,intended_title as "intendedTitle",intended_author as "intendedAuthor" from source_deposit where id=${uuid(id)}) d;`),
  listForOperations: (limit) => many(databaseUrl, `select row_to_json(d) from (select sd.id,sd.filename,sd.sha256,sd.declared_rights as "declaredRights",sd.intended_title as "intendedTitle",sd.intended_author as "intendedAuthor",sd.status,sd.created_at as "createdAt",sd.retrieved_at as "retrievedAt",sd.retrieved_by as "retrievedBy", row_to_json(dp) as parse from source_deposit sd left join lateral (select id,word_count as "wordCount",headings,suggested_title as "suggestedTitle",suggested_author as "suggestedAuthor",confidence,actor_id as actor,created_at as "createdAt" from deposit_parse where deposit_id=sd.id) dp on true order by sd.created_at desc limit ${int(limit)}) d;`),
  replaceDepositParse: async (proposal) => {
    const taskId = randomUUID(); const auditId = randomUUID();
    const result = await one(databaseUrl, `begin; with changed as (update source_deposit set status='parsed' where id=${uuid(proposal.depositId)} and status='retrieved' returning id), parsed as (insert into deposit_parse (id,deposit_id,word_count,headings,suggested_title,suggested_author,confidence,actor_id,created_at) select ${uuid(proposal.id)},id,${int(proposal.wordCount)},${textArray(proposal.headings)},${text(proposal.suggestedTitle)},${text(proposal.suggestedAuthor)},${text(proposal.confidence)},${uuid(proposal.actor)},${text(proposal.createdAt)}::timestamptz from changed on conflict (deposit_id) do update set word_count=excluded.word_count,headings=excluded.headings,suggested_title=excluded.suggested_title,suggested_author=excluded.suggested_author,confidence=excluded.confidence,actor_id=excluded.actor_id returning id), task as (insert into editorial_task (id,deposit_id,type,status,assignee_role) select ${uuid(taskId)},id,'catalogue-approval','open','literary-custodian' from changed returning id), audit as (insert into audit_event (id,type,subject_id,actor_id,actor_label) select ${uuid(auditId)},'deposit.parsed',id,${uuid(proposal.actor)},'user' from changed) select row_to_json(p) from (select (select id from parsed) as id) p; commit;`);
    if (!result?.id) throw new Error('Deposit is no longer in the required state.'); return proposal;
  },
}; }
